import { normalizeRecommendation } from '../schema';

/**
 * Investment / surplus-deployment recommendations.
 * The first five are migrated verbatim from
 * investSurplusLogic.computeInvestSurplusInsights (Deployment Insights, wired
 * into InvestSurplusReportContent). `wealthSip` is the wealth suggestion and
 * `increaseSips` is the ExecutiveSummary wealth-building action priority.
 */
export const INVESTMENT_RECOMMENDATIONS = [
  normalizeRecommendation({
    id: 'investments.readyToDeploy',
    title: 'Surplus Ready to Deploy',
    summary: 'You have {monthlyFreeCashDisplay}/month ready to deploy after savings.',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'informational',
    priority: 20,
    triggerId: 'HAS_FREE_CASH',
    reports: ['invest_surplus'],
    relatedDomains: ['savings', 'income'],
    relatedMetrics: ['monthlyFreeCash'],
    supportingMetrics: ['monthlyFreeCash', 'monthlyFreeCashDisplay'],
    tags: ['insight'],
    action: 'startSip',
  }),
  normalizeRecommendation({
    id: 'investments.yearEndSurplus',
    title: 'Projected Year-End Surplus',
    summary: '~{proratedUnallocatedDisplay} unallocated surplus projected through year-end.',
    category: 'investments',
    type: 'idleCash',
    severity: 'informational',
    priority: 30,
    triggerId: 'HAS_YEAR_SURPLUS',
    reports: ['invest_surplus'],
    relatedDomains: ['savings'],
    relatedMetrics: ['proratedUnallocated'],
    supportingMetrics: ['proratedUnallocated', 'proratedUnallocatedDisplay'],
    tags: ['insight'],
    action: 'startSip',
  }),
  normalizeRecommendation({
    id: 'investments.existingAllocations',
    title: 'Investments Already Planned',
    summary:
      '{allocationCount} investment allocation{allocationPlural} already planned ({monthlyCommittedDisplay}/month committed).',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'informational',
    priority: 40,
    triggerId: 'HAS_EXISTING_ALLOCATIONS',
    reports: ['invest_surplus'],
    relatedDomains: ['savings'],
    relatedMetrics: ['monthlyCommitted'],
    supportingMetrics: ['allocationCount', 'allocationPlural', 'monthlyCommittedDisplay', 'monthlyCommitted'],
    tags: ['insight'],
    action: 'monitor',
  }),
  normalizeRecommendation({
    id: 'investments.noAllocations',
    title: 'No Allocations Yet',
    summary:
      'No investment allocations planned yet — open the full allocation planner.',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'low',
    priority: 40,
    triggerId: 'NO_ALLOCATIONS',
    reports: ['invest_surplus'],
    relatedDomains: ['savings'],
    tags: ['insight'],
    action: 'startSip',
  }),
  normalizeRecommendation({
    id: 'investments.retirementHorizon',
    title: 'Long Runway to Retirement',
    summary:
      '{yearsToRetirement} years to retirement — consistent deployment now compounds over your full horizon.',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'informational',
    priority: 50,
    triggerId: 'HAS_RETIREMENT_HORIZON',
    reports: ['invest_surplus'],
    relatedDomains: ['savings', 'assumptions'],
    relatedFields: ['family.self.retirementAge'],
    relatedMetrics: ['yearsToRetirement'],
    supportingMetrics: ['yearsToRetirement'],
    tags: ['insight'],
    action: 'startSip',
  }),
  normalizeRecommendation({
    id: 'investments.wealthSip',
    title: 'Wealth building via SIP',
    summary: 'Direct {wealthMonthlyDisplay}/month into disciplined investments.',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'informational',
    priority: 15,
    triggerId: 'SIP_OPPORTUNITY',
    reports: ['put_your_money_to_work'],
    relatedDomains: ['savings'],
    relatedFields: ['savings.sip'],
    relatedMetrics: ['sipFutureValue'],
    supportingMetrics: ['wealthMonthly', 'wealthMonthlyDisplay', 'sipFutureValue'],
    businessMeaning:
      'Automated SIPs convert monthly surplus into long-term wealth through disciplined, compounding investment.',
    tags: ['suggestion', 'deferred'],
    action: 'startSip',
  }),
  normalizeRecommendation({
    id: 'investments.increaseSips',
    title: 'Increase Monthly SIPs',
    summary: 'Increase monthly SIPs and disciplined investments to improve wealth conversion.',
    category: 'investments',
    type: 'sipOpportunity',
    severity: 'high',
    priority: 40,
    triggerId: 'WEAK_WEALTH_BUILDING',
    reports: ['useful_insights'],
    relatedDomains: ['savings'],
    relatedFields: ['savings.sip'],
    relatedMetrics: ['investmentRatioPct'],
    businessMeaning:
      'Converting surplus into investments is how income becomes wealth; a low investment ratio slows every long-term goal.',
    tags: ['priority-next-step'],
    action: 'startSip',
  }),
];
