import { normalizeRecommendation } from '../schema';

/**
 * Protection recommendations.
 * Text migrated verbatim from SafetyNetLogic.buildRecoverySteps,
 * investSurplusLogic.buildInvestSurplusReport (protection suggestion) and
 * ExecutiveSummaryLogic action priorities.
 */
export const PROTECTION_RECOMMENDATIONS = [
  normalizeRecommendation({
    id: 'protection.lifeGap',
    title: 'Fill Protection Gap',
    summary: "Buy term cover of {protectionGapDisplay} to secure your family's future.",
    category: 'protection',
    type: 'protectionGap',
    severity: 'critical',
    priority: 10,
    triggerId: 'HAS_PROTECTION_GAP',
    reports: ['safety_net'],
    relatedDomains: ['protection', 'expenses'],
    relatedFields: ['protection.life.totalCover'],
    relatedMetrics: ['protectionGap', 'coverageRequired', 'coverageHave'],
    supportingMetrics: ['protectionGap', 'protectionGapDisplay'],
    businessMeaning:
      'Life cover replaces lost income so dependants can maintain their lifestyle if the earning member passes away (HLV method).',
    tags: ['recovery-step'],
    action: 'viewPlans',
  }),
  normalizeRecommendation({
    id: 'protection.healthAbsent',
    title: 'Get Family Health Cover',
    summary: 'Get family health insurance with at least {healthMinDisplay} sum insured.',
    category: 'protection',
    type: 'healthCoverage',
    severity: 'high',
    priority: 20,
    triggerId: 'HEALTH_COVER_ABSENT',
    reports: ['safety_net'],
    relatedDomains: ['protection'],
    relatedFields: ['protection.health.totalCover'],
    relatedMetrics: ['healthGap', 'minimumRequired'],
    supportingMetrics: ['healthMinDisplay', 'healthCoverRequired'],
    businessMeaning:
      'A single major hospitalization can cost several lakh; a family floater cover shields savings from medical shocks.',
    tags: ['recovery-step'],
    action: 'viewPlans',
  }),
  normalizeRecommendation({
    id: 'protection.healthPartial',
    title: 'Strengthen Health Cover',
    summary: 'Increase health cover by {healthGapDisplay} to reach the {healthMinDisplay} minimum.',
    category: 'protection',
    type: 'healthCoverage',
    severity: 'high',
    priority: 20,
    triggerId: 'HEALTH_COVER_PARTIAL',
    reports: ['safety_net'],
    relatedDomains: ['protection'],
    relatedFields: ['protection.health.totalCover'],
    relatedMetrics: ['healthGap', 'minimumRequired'],
    supportingMetrics: ['healthGap', 'healthGapDisplay', 'healthMinDisplay'],
    businessMeaning:
      'Topping up an existing but under-sized health cover keeps the family protected against rising treatment costs.',
    tags: ['recovery-step'],
    action: 'viewPlans',
  }),
  normalizeRecommendation({
    id: 'protection.closeCoverageGaps',
    title: 'Close Coverage Gaps',
    summary: 'Close life and health coverage gaps to protect your family against major risks.',
    category: 'protection',
    type: 'familyRisk',
    severity: 'high',
    priority: 30,
    triggerId: 'WEAK_FAMILY_PROTECTION',
    reports: ['useful_insights'],
    relatedDomains: ['protection'],
    relatedFields: ['protection.life.totalCover', 'protection.health.totalCover'],
    relatedMetrics: ['lifeCoverageRatioPct', 'healthCoverLakh'],
    businessMeaning:
      'Protection is the foundation of financial readiness; gaps here expose the family to the largest downside risks.',
    tags: ['priority-next-step'],
    action: 'learnMore',
  }),
  normalizeRecommendation({
    id: 'protection.investSurplusGap',
    title: 'Close the protection gap',
    summary: 'Life cover helps your family maintain lifestyle if income stops unexpectedly.',
    category: 'protection',
    type: 'protectionGap',
    severity: 'medium',
    priority: 40,
    triggerId: 'HAS_PROTECTION_GAP',
    reports: ['fix_your_financial_gaps'],
    relatedDomains: ['protection'],
    relatedFields: ['protection.life.totalCover'],
    relatedMetrics: ['protectionGap'],
    supportingMetrics: ['protectionGap', 'protectionGapDisplay'],
    businessMeaning:
      'Directing part of the deployable surplus toward term cover closes the HLV protection gap.',
    tags: ['suggestion', 'deferred'],
    action: 'viewPlans',
  }),
];
