import { normalizeCta } from './schema';

/**
 * Commercial CTA definitions — the single source of truth for commercial
 * actions. Only `contactFinbrella` is active today; every other CTA exists as
 * inactive metadata pending regulatory approval / platform integration.
 *
 * `emailTemplateRef: 'support_request'` points at the existing support email
 * flow (services/supportRequestEmailService.js). No new communication
 * infrastructure is introduced.
 */
export const COMMERCIAL_CTAS = [
  normalizeCta({
    id: 'contactFinbrella',
    label: 'Contact Finbrella for Help',
    description: 'Reach Finbrella for personalized assistance with this recommendation.',
    icon: 'send',
    actionType: 'contact',
    availability: 'active',
    regulatoryStatus: 'not_required',
    executionStrategy: 'email',
    analyticsEvent: 'cta_contact_finbrella',
    futureCapability: 'assistance.contactFinbrella',
    emailTemplateRef: 'support_request',
    payloadSchema: {
      userName: { type: 'string', required: false },
      userEmail: { type: 'string', required: false },
      moduleName: { type: 'string', required: true },
      userPhone: { type: 'string', required: false },
    },
    commercial: false,
    fallbackCtaId: null,
  }),

  // ── Inactive metadata (pending capability / regulatory activation) ──
  normalizeCta({
    id: 'learnMore',
    label: 'Learn More',
    description: 'Read an explainer about this recommendation.',
    icon: 'book-open',
    actionType: 'learn',
    availability: 'inactive',
    regulatoryStatus: 'not_required',
    executionStrategy: 'content',
    analyticsEvent: 'cta_learn_more',
    futureCapability: 'content.learnMore',
    payloadSchema: { topicId: { type: 'string', required: true } },
    commercial: false,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'monitorProgress',
    label: 'Monitor Progress',
    description: 'Track how this metric changes over time.',
    icon: 'activity',
    actionType: 'monitor',
    availability: 'inactive',
    regulatoryStatus: 'not_required',
    executionStrategy: 'track',
    analyticsEvent: 'cta_monitor_progress',
    futureCapability: 'insights.monitor',
    payloadSchema: { metricId: { type: 'string', required: true } },
    commercial: false,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'celebrate',
    label: 'Celebrate',
    description: 'Acknowledge a milestone the user has reached.',
    icon: 'party-popper',
    actionType: 'celebrate',
    availability: 'inactive',
    regulatoryStatus: 'not_required',
    executionStrategy: 'noop',
    analyticsEvent: 'cta_celebrate',
    futureCapability: 'insights.celebrate',
    payloadSchema: {},
    commercial: false,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'viewPlans',
    label: 'View Plans',
    description: 'Browse relevant product plans.',
    icon: 'list',
    actionType: 'view',
    availability: 'inactive',
    regulatoryStatus: 'pending',
    executionStrategy: 'navigate',
    analyticsEvent: 'cta_view_plans',
    futureCapability: 'commerce.viewPlans',
    payloadSchema: { productCategory: { type: 'string', required: true } },
    commercial: true,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'comparePlans',
    label: 'Compare Plans',
    description: 'Compare product plans side by side.',
    icon: 'columns',
    actionType: 'compare',
    availability: 'inactive',
    regulatoryStatus: 'pending',
    executionStrategy: 'navigate',
    analyticsEvent: 'cta_compare_plans',
    futureCapability: 'commerce.comparePlans',
    payloadSchema: { productCategory: { type: 'string', required: true } },
    commercial: true,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'buyProduct',
    label: 'Buy Product',
    description: 'Start a regulated product purchase journey.',
    icon: 'shopping-cart',
    actionType: 'buy',
    availability: 'inactive',
    regulatoryStatus: 'pending',
    executionStrategy: 'purchase_journey',
    analyticsEvent: 'cta_buy_product',
    futureCapability: 'commerce.buyProduct',
    payloadSchema: {
      productId: { type: 'string', required: true },
      productCategory: { type: 'string', required: true },
    },
    commercial: true,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'startSip',
    label: 'Start SIP',
    description: 'Begin a systematic investment plan.',
    icon: 'trending-up',
    actionType: 'sip',
    availability: 'inactive',
    regulatoryStatus: 'pending',
    executionStrategy: 'purchase_journey',
    analyticsEvent: 'cta_start_sip',
    futureCapability: 'commerce.startSip',
    payloadSchema: {
      amount: { type: 'number', required: true },
      fundId: { type: 'string', required: false },
    },
    commercial: true,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'increaseSip',
    label: 'Increase SIP',
    description: 'Increase an existing systematic investment plan.',
    icon: 'chevrons-up',
    actionType: 'increaseSip',
    availability: 'inactive',
    regulatoryStatus: 'pending',
    executionStrategy: 'purchase_journey',
    analyticsEvent: 'cta_increase_sip',
    futureCapability: 'commerce.increaseSip',
    payloadSchema: {
      amount: { type: 'number', required: true },
      sipId: { type: 'string', required: true },
    },
    commercial: true,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'uploadDocuments',
    label: 'Upload Documents',
    description: 'Provide documents needed to proceed.',
    icon: 'upload',
    actionType: 'upload',
    availability: 'inactive',
    regulatoryStatus: 'not_required',
    executionStrategy: 'upload',
    analyticsEvent: 'cta_upload_documents',
    futureCapability: 'documents.upload',
    payloadSchema: { documentType: { type: 'string', required: true } },
    commercial: false,
    fallbackCtaId: 'contactFinbrella',
  }),
  normalizeCta({
    id: 'bookConsultation',
    label: 'Book Consultation',
    description: 'Schedule a consultation with a Finbrella advisor.',
    icon: 'calendar',
    actionType: 'consult',
    availability: 'inactive',
    regulatoryStatus: 'not_required',
    executionStrategy: 'schedule',
    analyticsEvent: 'cta_book_consultation',
    futureCapability: 'advisory.bookConsultation',
    payloadSchema: { topic: { type: 'string', required: false } },
    commercial: false,
    fallbackCtaId: 'contactFinbrella',
  }),
];
