/**
 * Chart registry — modules render charts by id from executive payload series.
 */

export const CHART_DEFINITIONS = [
  {
    id: 'users_by_day',
    title: 'New Users Trend',
    seriesKey: 'usersByDay',
    type: 'line',
    modules: ['executive', 'users'],
    drilldownMetricId: 'new_users',
    xKey: 'date',
    yKey: 'value',
  },
  {
    id: 'funnel_steps',
    title: 'WealthMap Funnel',
    seriesKey: 'funnelSteps',
    type: 'bar',
    modules: ['executive', 'funnel'],
    drilldownMetricId: 'wealthmap_incomplete',
    xKey: 'label',
    yKey: 'count',
  },
  {
    id: 'wellness_distribution',
    title: 'Wellness Score Distribution',
    seriesKey: 'wellnessDistribution',
    type: 'bar',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'low_wellness',
    xKey: 'bucket',
    yKey: 'count',
  },
  {
    id: 'net_worth_trend',
    title: 'Average Net Worth by Month',
    seriesKey: 'netWorthTrend',
    type: 'area',
    modules: ['executive', 'financial', 'investment'],
    drilldownMetricId: 'high_net_worth',
    xKey: 'date',
    yKey: 'value',
  },
  {
    id: 'events_by_day',
    title: 'Events by Day',
    seriesKey: 'eventsByDay',
    type: 'line',
    modules: ['engagement', 'product', 'ai'],
    drilldownMetricId: 'total_users',
    xKey: 'date',
    yKey: 'value',
    source: 'events',
  },
  {
    id: 'top_screens',
    title: 'Most Visited Screens',
    seriesKey: 'topScreens',
    type: 'bar',
    modules: ['engagement', 'product'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'top_reports',
    title: 'Most Viewed Reports',
    seriesKey: 'topReports',
    type: 'bar',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'top_features',
    title: 'Top Features / CTAs',
    seriesKey: 'topFeatures',
    type: 'bar',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'top_ctas',
    title: 'CTA Click Breakdown',
    seriesKey: 'topCtas',
    type: 'bar',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'least_reports',
    title: 'Least Viewed Reports',
    seriesKey: 'leastReports',
    type: 'bar',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'report_durations',
    title: 'Avg Time per Report',
    seriesKey: 'reportDurations',
    type: 'bar',
    modules: ['product', 'engagement'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'avgDurationSec',
    source: 'events',
  },
  {
    id: 'activity_by_hour',
    title: 'Activity by Hour (IST)',
    seriesKey: 'activityByHour',
    type: 'bar',
    modules: ['engagement'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'smart_edit_fields',
    title: 'Most Edited Fields',
    seriesKey: 'smartEditFields',
    type: 'bar',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
  {
    id: 'recommendation_actions',
    title: 'Recommendation Actions',
    seriesKey: 'recommendationActions',
    type: 'bar',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    xKey: 'label',
    yKey: 'count',
    source: 'events',
  },
];

export function getChartsForModule(moduleId) {
  return CHART_DEFINITIONS.filter((c) => c.modules.includes(moduleId));
}
