/**
 * KPI registry — add metrics without changing page layouts.
 * Each KPI declares format, drilldown target, and which modules surface it.
 */

export const KPI_FORMAT = {
  NUMBER: 'number',
  PERCENT: 'percent',
  CURRENCY: 'currency',
  TEXT: 'text',
};

/** @typedef {{
 *  id: string,
 *  label: string,
 *  description?: string,
 *  format: string,
 *  group: string,
 *  modules: string[],
 *  drilldownMetricId: string,
 *  kpiKey: string,
 *  phase?: number,
 *  unavailableKey?: string,
 * }} KpiDefinition */

/** @type {KpiDefinition[]} */
export const KPI_DEFINITIONS = [
  // Business
  {
    id: 'total_users',
    label: 'Total Users',
    format: KPI_FORMAT.NUMBER,
    group: 'Business',
    modules: ['executive', 'users'],
    drilldownMetricId: 'total_users',
    kpiKey: 'totalUsers',
  },
  {
    id: 'new_users',
    label: 'New Users',
    format: KPI_FORMAT.NUMBER,
    group: 'Business',
    modules: ['executive', 'users'],
    drilldownMetricId: 'new_users',
    kpiKey: 'newUsers',
  },
  {
    id: 'active_users',
    label: 'Active Users',
    description: 'Available after session instrumentation (Phase 2)',
    format: KPI_FORMAT.NUMBER,
    group: 'Business',
    modules: ['executive', 'users', 'engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'activeUsers',
    unavailableKey: 'activeUsersAvailable',
    phase: 2,
  },
  {
    id: 'wealthmap_completion',
    label: 'WealthMap Completion %',
    format: KPI_FORMAT.PERCENT,
    group: 'Business',
    modules: ['executive', 'funnel'],
    drilldownMetricId: 'wealthmap_completed',
    kpiKey: 'wealthmapCompletionPct',
  },
  {
    id: 'revenue',
    label: 'Revenue',
    format: KPI_FORMAT.CURRENCY,
    group: 'Business',
    modules: ['executive', 'revenue'],
    drilldownMetricId: 'subscribed',
    kpiKey: 'revenue',
  },
  {
    id: 'subscription_pct',
    label: 'Subscription %',
    format: KPI_FORMAT.PERCENT,
    group: 'Business',
    modules: ['executive', 'revenue', 'users'],
    drilldownMetricId: 'subscribed',
    kpiKey: 'subscriptionPct',
  },
  {
    id: 'advisor_count',
    label: 'Advisors',
    format: KPI_FORMAT.NUMBER,
    group: 'Business',
    modules: ['executive', 'advisors'],
    drilldownMetricId: 'advised',
    kpiKey: 'advisorCount',
  },
  {
    id: 'advised_clients',
    label: 'Advised Clients',
    format: KPI_FORMAT.NUMBER,
    group: 'Business',
    modules: ['executive', 'advisors'],
    drilldownMetricId: 'advised',
    kpiKey: 'advisedClients',
  },

  // Financial Intelligence
  {
    id: 'avg_wellness',
    label: 'Avg Financial Wellness',
    format: KPI_FORMAT.NUMBER,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'low_wellness',
    kpiKey: 'avgWellnessScore',
  },
  {
    id: 'avg_net_worth',
    label: 'Average Net Worth',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial', 'investment'],
    drilldownMetricId: 'high_net_worth',
    kpiKey: 'avgNetWorth',
  },
  {
    id: 'avg_monthly_surplus',
    label: 'Avg Monthly Surplus',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'total_users',
    kpiKey: 'avgMonthlySurplus',
  },
  {
    id: 'avg_sip',
    label: 'Current SIP (Avg)',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial', 'investment'],
    drilldownMetricId: 'has_sip',
    kpiKey: 'avgSip',
  },
  {
    id: 'avg_unallocated',
    label: 'Unallocated Surplus',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'total_users',
    kpiKey: 'avgUnallocatedSurplus',
  },
  {
    id: 'avg_protection_gap',
    label: 'Protection Gap',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial', 'investment'],
    drilldownMetricId: 'protection_gap',
    kpiKey: 'avgProtectionGap',
  },
  {
    id: 'avg_health_gap',
    label: 'Health Insurance Gap',
    format: KPI_FORMAT.CURRENCY,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial', 'investment'],
    drilldownMetricId: 'health_gap',
    kpiKey: 'avgHealthInsuranceGap',
  },
  {
    id: 'users_with_goals',
    label: 'Goal Completion Gap',
    description: '% of users without goals defined',
    format: KPI_FORMAT.PERCENT,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'no_goals',
    kpiKey: 'goalCompletionGapPct',
  },
  {
    id: 'retirement_readiness',
    label: 'Retirement Readiness',
    description: 'Average goal-readiness pillar score (0–20) from readiness snapshots',
    format: KPI_FORMAT.NUMBER,
    group: 'Financial Intelligence',
    modules: ['executive', 'financial'],
    drilldownMetricId: 'low_wellness',
    kpiKey: 'avgRetirementReadinessScore',
  },
  {
    id: 'vehicle_insurance',
    label: 'Vehicle Insurance Coverage',
    format: KPI_FORMAT.PERCENT,
    group: 'Financial Intelligence',
    modules: ['executive', 'investment'],
    drilldownMetricId: 'has_vehicle_insurance',
    kpiKey: 'vehicleInsuranceCoveragePct',
  },
  {
    id: 'portfolio_life',
    label: 'Portfolio includes Life Insurance',
    format: KPI_FORMAT.PERCENT,
    group: 'Financial Intelligence',
    modules: ['executive', 'investment'],
    drilldownMetricId: 'portfolio_life_insurance',
    kpiKey: 'portfolioIncludesLifeInsurancePct',
  },

  // Journey
  {
    id: 'funnel_completion',
    label: 'Funnel Completion',
    format: KPI_FORMAT.PERCENT,
    group: 'Journey',
    modules: ['executive', 'funnel'],
    drilldownMetricId: 'wealthmap_completed',
    kpiKey: 'funnelCompletionPct',
  },

  // Phase 2 — Engagement
  {
    id: 'session_count',
    label: 'Session Count',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'session_count',
    phase: 2,
  },
  {
    id: 'dau',
    label: 'DAU',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement', 'executive'],
    drilldownMetricId: 'total_users',
    kpiKey: 'dau',
    phase: 2,
  },
  {
    id: 'wau',
    label: 'WAU',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'wau',
    phase: 2,
  },
  {
    id: 'mau',
    label: 'MAU',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'mau',
    phase: 2,
  },
  {
    id: 'avg_screen_duration',
    label: 'Avg Screen Duration (ms)',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'avg_screen_duration_ms',
    phase: 2,
  },
  {
    id: 'screen_views',
    label: 'Screen Views',
    format: KPI_FORMAT.NUMBER,
    group: 'Product',
    modules: ['product', 'engagement'],
    drilldownMetricId: 'total_users',
    kpiKey: 'screen_views',
    phase: 2,
  },
  {
    id: 'report_views',
    label: 'Report Views',
    format: KPI_FORMAT.NUMBER,
    group: 'Product',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'report_views',
    phase: 2,
  },
  {
    id: 'feature_clicks',
    label: 'Feature Clicks',
    format: KPI_FORMAT.NUMBER,
    group: 'Product',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'feature_clicks',
    phase: 2,
  },
  {
    id: 'cta_clicks',
    label: 'CTA Clicks',
    format: KPI_FORMAT.NUMBER,
    group: 'Product',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'cta_clicks',
    phase: 2,
  },
  {
    id: 'smart_edit_opens',
    label: 'Smart Edit Opens',
    format: KPI_FORMAT.NUMBER,
    group: 'AI',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    kpiKey: 'smart_edit_opens',
    phase: 2,
  },
  {
    id: 'smart_edit_saves',
    label: 'Smart Edit Saves',
    format: KPI_FORMAT.NUMBER,
    group: 'AI',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    kpiKey: 'smart_edit_saves',
    phase: 2,
  },
  {
    id: 'recommendation_views',
    label: 'Recommendations Viewed',
    format: KPI_FORMAT.NUMBER,
    group: 'AI',
    modules: ['ai', 'product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'recommendation_views',
    phase: 2,
  },
  {
    id: 'recommendation_accepts',
    label: 'Recommendations Accepted',
    format: KPI_FORMAT.NUMBER,
    group: 'AI',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    kpiKey: 'recommendation_accepts',
    phase: 2,
  },
  {
    id: 'recommendation_accept_rate',
    label: 'Recommendation Accept Rate',
    format: KPI_FORMAT.PERCENT,
    group: 'AI',
    modules: ['ai', 'executive'],
    drilldownMetricId: 'total_users',
    kpiKey: 'recommendation_accept_rate',
    phase: 2,
  },
  {
    id: 'avg_report_duration',
    label: 'Avg Report Time (ms)',
    format: KPI_FORMAT.NUMBER,
    group: 'Engagement',
    modules: ['engagement', 'product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'avg_report_duration_ms',
    phase: 2,
  },
  {
    id: 'smart_edit_save_rate',
    label: 'Smart Edit Save Rate',
    format: KPI_FORMAT.PERCENT,
    group: 'AI',
    modules: ['ai'],
    drilldownMetricId: 'total_users',
    kpiKey: 'smart_edit_save_rate',
    phase: 2,
  },
  {
    id: 'report_to_cta_rate',
    label: 'Report → CTA Rate',
    description: 'CTA clicks as % of report views (help-seeking intensity)',
    format: KPI_FORMAT.PERCENT,
    group: 'Product',
    modules: ['product'],
    drilldownMetricId: 'total_users',
    kpiKey: 'report_to_cta_rate',
    phase: 2,
  },
];

export function getKpisForModule(moduleId) {
  return KPI_DEFINITIONS.filter((k) => k.modules.includes(moduleId));
}

export function getKpiById(id) {
  return KPI_DEFINITIONS.find((k) => k.id === id);
}
