import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const ASSET_FIELDS = [
  normalizeField({
    id: 'assets.portfolioValue',
    kind: 'field',
    label: 'Investment Portfolio Value',
    shortLabel: 'Portfolio',
    aliases: ['portfolio', 'investments value', 'mutual funds value', 'stocks value'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    searchBoost: 14,
    businessMeaning:
      'Snapshot of current investment corpus used in net worth, future-self, and allocation context. Detailed Flow breaks this into instrument lines.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'assetCategories.summaryPortfolioValue',
      refinements: {
        syncModule: 'wealthDetailSync',
        detailPaths: ['assetCategories.investments'],
        reconciliation: 'summaryVsDetailSum',
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.netWorth',
    ],
    tags: ['balance-sheet', 'investments'],
  }),

  normalizeField({
    id: 'assets.emergencyFund',
    kind: 'field',
    label: 'Liquid Cash / Emergency Fund',
    shortLabel: 'Emergency Fund',
    aliases: ['emergency', 'liquid cash', 'cash buffer', 'contingency fund', 'rainy day'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 16,
    businessMeaning:
      'Readily available cash used by contingency gap analysis and protection-first allocation recommendations.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'assetCategories.summaryLiquidCash',
      refinements: {
        syncModule: 'wealthDetailSync',
        detailPaths: ['assetCategories.cash'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: [
      'report.summary.safety_net',
      'report.detail.put_your_money_to_work',
      'engine.contingency',
      'engine.gapEngine',
      'engine.allocation',
    ],
    tags: ['balance-sheet', 'protection'],
  }),

  normalizeField({
    id: 'assets.realEstateValue',
    kind: 'field',
    label: 'Real Estate / High-value Assets',
    shortLabel: 'Real Estate',
    aliases: ['property', 'house value', 'real estate', 'home value'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    searchBoost: 8,
    businessMeaning:
      'Illiquid high-value asset snapshot contributing to net worth; refined into property lines in Detailed Flow.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'assetCategories.summaryRealEstateAssets',
      refinements: {
        syncModule: 'wealthDetailSync',
        detailPaths: ['assetCategories.realEstate'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: ['report.summary.future_self', 'engine.netWorth'],
    tags: ['balance-sheet'],
  }),

  // --- Phase 2: Asset breakdown, FD modal, custom assets ---

  normalizeField({
    id: 'assets.realEstate.residential',
    kind: 'field',
    label: 'Residential House',
    shortLabel: 'Home',
    aliases: ['house', 'residential property', 'primary home'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Primary residence value in the wealth asset breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: {
      path: 'assetCategories.realEstate.residential',
      refinements: { syncModule: 'wealthDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    relatedFieldIds: ['assets.realEstateValue'],
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'assets.investments.equity',
    kind: 'field',
    label: 'Equity Investments (Stocks, ETFs)',
    shortLabel: 'Equity',
    aliases: ['stocks', 'etf', 'equity portfolio'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    businessMeaning: 'Direct equity holdings contributing to portfolio and net worth.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'assetCategories.investments.equity' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    relatedFieldIds: ['assets.portfolioValue'],
    impacts: ['engine.netWorth', 'report.detail.put_your_money_to_work'],
  }),

  normalizeField({
    id: 'assets.investments.mutualFunds',
    kind: 'field',
    label: 'Mutual Funds Portfolio',
    shortLabel: 'Mutual Funds',
    aliases: ['mf portfolio', 'mutual fund value'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    businessMeaning: 'Mutual fund corpus in the asset breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'assetCategories.investments.mutualFunds' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    relatedFieldIds: ['assets.portfolioValue'],
    impacts: ['engine.netWorth', 'report.detail.put_your_money_to_work'],
  }),

  normalizeField({
    id: 'assets.cash.savings',
    kind: 'field',
    label: 'Bank Savings',
    shortLabel: 'Bank Savings',
    aliases: ['savings account', 'bank balance'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    businessMeaning: 'Bank savings contributing to liquid / emergency fund views.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'assetCategories.cash.savings' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    relatedFieldIds: ['assets.emergencyFund'],
    impacts: ['report.summary.safety_net', 'engine.contingency', 'engine.netWorth'],
  }),

  normalizeField({
    id: 'assets.fixedDeposits',
    kind: 'collection',
    label: 'Fixed Deposits',
    shortLabel: 'FD',
    aliases: ['fd', 'fixed deposit'],
    domain: 'assets',
    uiCategory: 'assets',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Fixed deposit instruments with amount/duration via investment details modal.',
    editExperience: {
      type: 'modal',
      modalId: 'investmentDetails',
      collectionId: 'assets.fixedDeposits',
    },
    state: { path: 'assetCategories.investments.fixedDeposit', idKey: 'id' },
    itemFieldIds: ['assets.fixedDeposit.amount'],
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    impacts: ['engine.netWorth'],
    tags: ['modal'],
  }),

  normalizeField({
    id: 'assets.fixedDeposit.amount',
    kind: 'collectionItemField',
    collectionId: 'assets.fixedDeposits',
    label: 'FD amount',
    shortLabel: 'FD amount',
    aliases: ['fixed deposit amount'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Principal amount of a fixed deposit.',
    editExperience: {
      type: 'modal',
      modalId: 'investmentDetails',
      collectionId: 'assets.fixedDeposits',
    },
    state: { path: 'amount' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'assets.retirement.epf',
    kind: 'field',
    label: 'EPF balance',
    shortLabel: 'EPF',
    aliases: ['epf', 'provident fund'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'low',
    businessMeaning: 'EPF corpus contributing to retirement readiness and net worth.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'assetCategories.retirement.epf' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'assets-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    impacts: ['engine.retirementHorizon', 'engine.netWorth'],
  }),

  normalizeField({
    id: 'assets.custom',
    kind: 'collection',
    label: 'Custom assets',
    shortLabel: 'Custom assets',
    aliases: ['other assets', 'additional assets'],
    domain: 'assets',
    uiCategory: 'assets',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'User-defined asset lines included in net worth.',
    editExperience: { type: 'collection' },
    state: { path: 'assetCategories.custom', idKey: 'id' },
    itemFieldIds: ['assets.custom.value'],
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'custom-assets',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'assets.custom.value',
    kind: 'collectionItemField',
    collectionId: 'assets.custom',
    label: 'Custom asset value',
    shortLabel: 'Asset value',
    aliases: ['custom asset amount'],
    domain: 'assets',
    uiCategory: 'assets',
    valueType: 'currency',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'Value of a user-defined asset line.',
    editExperience: { type: 'collection', collectionId: 'assets.custom' },
    state: { path: 'value' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.ASSETS,
        questionId: 'current-assets',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'custom-assets',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'summary' },
    impacts: ['engine.netWorth'],
  }),
];
