import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const DEBT_FIELDS = [
  normalizeField({
    id: 'debt.hasEmi',
    kind: 'field',
    label: 'Do you have ongoing EMI commitments?',
    shortLabel: 'Has EMI?',
    aliases: ['emi', 'loan emi', 'installments', 'have loans'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'boolean',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 10,
    businessMeaning:
      'Gate for EMI burden and outstanding loan capture. Affects cash-flow surplus and liability sections.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['debt.hasEmi', 'debt.emi.monthlyTotal'],
    },
    state: { path: 'hasEMI' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'emi-commitments',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'recap-emi',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['debt.emi.monthlyTotal', 'liabilities.outstandingLoans'],
    impacts: [
      'report.summary.money_story',
      'report.detail.your_money_flow',
      'engine.cashFlow',
    ],
    tags: ['gate', 'debt'],
  }),

  normalizeField({
    id: 'debt.emi.monthlyTotal',
    kind: 'field',
    label: 'Total monthly EMI burden',
    shortLabel: 'Monthly EMI',
    aliases: ['emi amount', 'loan payment', 'monthly loan', 'installment amount'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 14,
    businessMeaning:
      'Fixed monthly debt service reduced from surplus; refined into per-loan EMI details in Detailed Flow.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['debt.hasEmi', 'debt.emi.monthlyTotal'],
    },
    visibility: {
      allOf: [{ field: 'debt.hasEmi', eq: true }],
    },
    state: {
      path: 'expenseCategories.summaryEmiTotal',
      refinements: {
        syncModule: 'expenseDetailSync',
        detailPaths: ['expenseCategories.emi'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'emi-commitments',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loans',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    relatedFieldIds: ['debt.hasEmi', 'liabilities.outstandingLoans'],
    impacts: [
      'report.summary.money_story',
      'report.detail.your_money_flow',
      'engine.cashFlow',
      'engine.allocation',
    ],
    tags: ['recurring-cashflow', 'debt'],
  }),

  // --- Phase 2: EMI loan types + modal collection ---

  normalizeField({
    id: 'debt.emi.selectedLoanTypes',
    kind: 'field',
    label: 'EMI loan types',
    shortLabel: 'Loan types',
    aliases: ['home loan', 'car loan', 'personal loan', 'education loan', 'loan types'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'enum',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning:
      'Selects which EMI instruments exist so detailed loan terms and outstanding amounts can be captured.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'debt.hasEmi', eq: true }] },
    state: { path: 'expenseCategories.selectedEmiLoanTypes' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loan-types',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['debt.emi.loans'],
    impacts: ['engine.cashFlow', 'engine.debt'],
    tags: ['debt', 'gate'],
  }),

  normalizeField({
    id: 'debt.emi.loans',
    kind: 'collection',
    label: 'EMI loan details',
    shortLabel: 'Loan details',
    aliases: ['loan terms', 'emi details', 'loan tenure', 'interest rate'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    importance: 'critical',
    quickEditPriority: 'medium',
    searchBoost: 10,
    businessMeaning:
      'Per-loan principal, rate, tenure and start date used to compute EMI and outstanding liability.',
    editExperience: {
      type: 'modal',
      modalId: 'loanDetails',
      collectionId: 'debt.emi.loans',
    },
    visibility: { allOf: [{ field: 'debt.hasEmi', eq: true }] },
    state: { path: 'expenseCategories.emi', idKey: 'loanKey' },
    itemFieldIds: [
      'debt.emi.loan.principal',
      'debt.emi.loan.rate',
      'debt.emi.loan.tenure',
    ],
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loans',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['debt.emi.monthlyTotal', 'debt.emi.selectedLoanTypes'],
    impacts: [
      'report.detail.your_money_flow',
      'engine.cashFlow',
      'engine.debt',
      'engine.allocation',
    ],
    tags: ['debt', 'modal'],
  }),

  normalizeField({
    id: 'debt.emi.loan.principal',
    kind: 'collectionItemField',
    collectionId: 'debt.emi.loans',
    label: 'Original Loan Amount',
    shortLabel: 'Principal',
    aliases: ['loan amount', 'principal'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning: 'Original principal for an EMI loan instrument.',
    editExperience: { type: 'modal', modalId: 'loanDetails', collectionId: 'debt.emi.loans' },
    state: { path: 'principal' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loans',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.debt'],
  }),

  normalizeField({
    id: 'debt.emi.loan.rate',
    kind: 'collectionItemField',
    collectionId: 'debt.emi.loans',
    label: 'Interest Rate (%)',
    shortLabel: 'Rate',
    aliases: ['interest', 'loan rate', 'roi'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'percent',
    importance: 'high',
    quickEditPriority: 'low',
    businessMeaning: 'Annual interest rate used to compute EMI for the loan.',
    editExperience: { type: 'modal', modalId: 'loanDetails', collectionId: 'debt.emi.loans' },
    state: { path: 'rate' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loans',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.debt'],
  }),

  normalizeField({
    id: 'debt.emi.loan.tenure',
    kind: 'collectionItemField',
    collectionId: 'debt.emi.loans',
    label: 'Total Tenure (Months)',
    shortLabel: 'Tenure',
    aliases: ['tenure', 'loan months', 'loan duration'],
    domain: 'debt',
    uiCategory: 'loans_liabilities',
    valueType: 'number',
    importance: 'high',
    quickEditPriority: 'low',
    businessMeaning: 'Total loan tenure in months used with rate and principal to compute EMI.',
    editExperience: { type: 'modal', modalId: 'loanDetails', collectionId: 'debt.emi.loans' },
    state: { path: 'tenure' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'emi-loans',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.debt'],
  }),
];
