import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const EXPENSE_FIELDS = [
  normalizeField({
    id: 'expenses.household.monthlyTotal',
    kind: 'field',
    label: 'Monthly household expenses',
    shortLabel: 'Household Spend',
    aliases: ['expenses', 'monthly spend', 'household cost', 'living expenses', 'lifestyle'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'critical',
    searchBoost: 18,
    businessMeaning:
      'Core outflow for surplus calculation, contingency sizing, and lifestyle sustainability across summary and detailed reports.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: {
      path: 'expenseCategories.summaryHouseholdTotal',
      refinements: {
        syncModule: 'expenseDetailSync',
        detailPaths: ['expenseCategories.household'],
        reconciliation: 'summaryVsDetailSum',
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'monthly-outflows',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: {
      whenCapabilitySummary: 'summary',
      whenCapabilityFull: 'detailed',
    },
    impacts: [
      'report.summary.money_story',
      'report.summary.safety_net',
      'report.detail.your_money_flow',
      'engine.cashFlow',
      'engine.contingency',
    ],
    tags: ['recurring-cashflow'],
  }),

  normalizeField({
    id: 'expenses.insurance.monthlyPremiumTotal',
    kind: 'field',
    label: 'Monthly insurance premiums',
    shortLabel: 'Insurance Premiums',
    aliases: ['premium', 'insurance cost', 'insurance payment'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 8,
    businessMeaning:
      'Monthly protection spend deducted in cash-flow and surplus views; refined later by per-policy premiums in Detailed Flow.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'expenseCategories.summaryInsuranceTotal',
      refinements: {
        syncModule: 'insuranceDetailSync',
        detailPaths: ['expenseCategories.insurance'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'monthly-outflows',
        capability: 'summary',
        role: 'primary',
      },
    ],
    impacts: [
      'report.summary.money_story',
      'report.summary.safety_net',
      'report.detail.your_money_flow',
      'engine.cashFlow',
    ],
    tags: ['recurring-cashflow', 'insurance'],
  }),

  // --- Phase 2: Household breakdown lines ---

  normalizeField({
    id: 'expenses.household.grocery',
    kind: 'field',
    label: 'Household (Grocery, LPG, Fuel etc.)',
    shortLabel: 'Grocery & essentials',
    aliases: ['grocery', 'fuel', 'lpg', 'household breakup'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Core household essentials line in the detailed expense breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: {
      path: 'expenseCategories.household.grocery',
      refinements: { syncModule: 'expenseDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['expenses.household.monthlyTotal'],
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'expenses.household.rent',
    kind: 'field',
    label: 'House Rent',
    shortLabel: 'Rent',
    aliases: ['rent', 'house rent'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning: 'Monthly housing rent in the detailed household breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'expenseCategories.household.rent' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['expenses.household.monthlyTotal'],
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'expenses.household.lifestyle',
    kind: 'field',
    label: 'Lifestyle (Shopping, Movies, Dinner etc.)',
    shortLabel: 'Lifestyle',
    aliases: ['lifestyle', 'shopping', 'dining'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'high',
    businessMeaning: 'Discretionary lifestyle spend in the household breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'expenseCategories.household.lifestyle' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['expenses.household.monthlyTotal'],
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'expenses.household.medical',
    kind: 'field',
    label: 'Medical Expenses',
    shortLabel: 'Medical',
    aliases: ['medical', 'healthcare spend', 'doctor'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Recurring medical spend in the household breakup (separate from health premiums).',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'expenseCategories.household.medical' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'expenses.household.travel',
    kind: 'field',
    label: 'Travel',
    shortLabel: 'Travel',
    aliases: ['commute', 'travel expense'],
    domain: 'expenses',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'Travel spend line in the detailed household breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'expenseCategories.household.travel' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.cashFlow'],
  }),
];
