import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const FAMILY_FIELDS = [
  normalizeField({
    id: 'family.self.name',
    kind: 'field',
    label: 'Name',
    shortLabel: 'Name',
    aliases: ['full name', 'your name'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'high',
    quickEditPriority: 'low',
    searchBoost: 5,
    businessMeaning:
      'Primary identity for the plan holder. Used in reports, insurance policy matching, and personalized messaging.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['family.self.name', 'family.self.mobile'],
    },
    state: { path: 'familyMembers[relation=Self].name' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.PROFILE,
        questionId: 'personal-details',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['family.self.mobile'],
    impacts: ['report.summary.money_story', 'report.detail.your_money_flow'],
    tags: ['identity'],
  }),

  normalizeField({
    id: 'family.self.mobile',
    kind: 'field',
    label: 'Mobile',
    shortLabel: 'Mobile',
    aliases: ['phone', 'phone number', 'mobile number', 'contact'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'tel',
    importance: 'medium',
    quickEditPriority: 'low',
    searchBoost: 3,
    businessMeaning:
      'Contact number for the plan holder. Used for account identity and support; not a planning engine input.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['family.self.name', 'family.self.mobile'],
    },
    state: { path: 'familyMembers[relation=Self].mobile' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.PROFILE,
        questionId: 'personal-details',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['family.self.name'],
    impacts: [],
    tags: ['identity', 'pii'],
  }),

  normalizeField({
    id: 'family.self.dob',
    kind: 'field',
    label: 'Date of Birth',
    shortLabel: 'DOB',
    aliases: ['birthday', 'birth date', 'age', 'date of birth'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'date',
    importance: 'critical',
    quickEditPriority: 'low',
    searchBoost: 15,
    businessMeaning:
      'Anchors current age for retirement horizon, life-stage projections, goal timelines, and age-dependent recommendations.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['family.self.dob', 'family.self.retirementAge'],
    },
    state: { path: 'familyMembers[relation=Self].dob' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.PROFILE,
        questionId: 'personal-details',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['family.self.retirementAge'],
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.retirementHorizon',
      'engine.gapEngine',
    ],
    tags: ['identity', 'planning-horizon'],
  }),

  normalizeField({
    id: 'family.self.retirementAge',
    kind: 'field',
    label: 'Retirement Age',
    shortLabel: 'Retire at',
    aliases: ['retire', 'retirement', 'when to retire', 'retirement age'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'number',
    importance: 'critical',
    quickEditPriority: 'low',
    searchBoost: 12,
    businessMeaning:
      'Defines the planning horizon for retirement corpus, surplus allocation, and years-to-retirement calculations.',
    editExperience: {
      type: 'question',
      hostsFieldIds: ['family.self.dob', 'family.self.retirementAge'],
    },
    validation: { required: true, min: 40, max: 60 },
    state: { path: 'familyMembers[relation=Self].retirementAge' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.PROFILE,
        questionId: 'personal-details',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['family.self.dob'],
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.retirementHorizon',
      'engine.gapEngine',
    ],
    tags: ['planning-horizon'],
  }),

  normalizeField({
    id: 'family.self.employmentType',
    kind: 'field',
    label: 'Occupation / Employment Type',
    shortLabel: 'Occupation',
    aliases: ['job', 'salaried', 'business', 'profession', 'employment', 'work type'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'enum',
    importance: 'high',
    quickEditPriority: 'low',
    searchBoost: 8,
    businessMeaning:
      'Selects income capture path (salary vs business/profession) and later detailed tax/employment questions. Summary occupation maps to detailed employmentType via sync.',
    editExperience: { type: 'question' },
    state: {
      path: 'familyMembers[relation=Self].occupation',
      legacyPaths: ['familyMembers[relation=Self].employmentType'],
      refinements: { syncModule: 'employmentTypeSync' },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.PROFILE,
        questionId: 'occupation',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'self-profile',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: {
      whenCapabilitySummary: 'summary',
      whenCapabilityFull: 'detailed',
    },
    impacts: ['report.summary.money_story', 'report.detail.your_money_flow', 'engine.income'],
    tags: ['identity', 'income-path'],
  }),

  // --- Phase 2: Detailed-only family fields & children collection ---

  normalizeField({
    id: 'family.self.isMarried',
    kind: 'field',
    label: 'Are you married?',
    shortLabel: 'Married?',
    aliases: ['married', 'marital status', 'spouse'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'boolean',
    importance: 'high',
    quickEditPriority: 'low',
    searchBoost: 6,
    businessMeaning:
      'Gate for spouse and children capture. Affects household income paths and dependent education planning.',
    editExperience: { type: 'question' },
    state: { path: 'familyMembers[relation=Self].isMarried' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'self-profile',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.household'],
    tags: ['identity', 'gate'],
  }),

  normalizeField({
    id: 'family.self.organizationName',
    kind: 'field',
    label: 'Organization / Business name',
    shortLabel: 'Organization',
    aliases: ['company', 'employer', 'department', 'business name'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'low',
    quickEditPriority: 'low',
    searchBoost: 2,
    businessMeaning: 'Employer or business context for the plan holder; supporting profile detail.',
    editExperience: { type: 'question' },
    state: { path: 'familyMembers[relation=Self].organizationName' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'self-profile',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
    tags: ['identity'],
  }),

  normalizeField({
    id: 'family.self.natureOfBusiness',
    kind: 'field',
    label: 'Nature of Work',
    shortLabel: 'Nature of Work',
    aliases: ['nature of business', 'work nature'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'low',
    quickEditPriority: 'low',
    businessMeaning: 'Describes the nature of employment or business for profile completeness.',
    editExperience: { type: 'question' },
    state: { path: 'familyMembers[relation=Self].natureOfBusiness' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'self-profile',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
  }),

  normalizeField({
    id: 'family.self.educationalQualification',
    kind: 'field',
    label: 'Educational Qualification',
    shortLabel: 'Education',
    aliases: ['qualification', 'degree', 'education level'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'low',
    quickEditPriority: 'low',
    businessMeaning: 'Educational background of the plan holder; supporting profile detail.',
    editExperience: { type: 'question' },
    state: { path: 'familyMembers[relation=Self].educationalQualification' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'self-profile',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
  }),

  normalizeField({
    id: 'family.spouse.name',
    kind: 'field',
    label: 'Spouse Name',
    shortLabel: 'Spouse Name',
    aliases: ['partner name', 'wife name', 'husband name'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Identifies the spouse member for household planning and insurance coverage blocks.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'family.self.isMarried', eq: true }] },
    state: { path: 'familyMembers[relation=Spouse].name' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-details',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['family.spouse.dob', 'family.spouse.mobile'],
    impacts: [],
    tags: ['identity'],
  }),

  normalizeField({
    id: 'family.spouse.dob',
    kind: 'field',
    label: 'Spouse Date of Birth',
    shortLabel: 'Spouse DOB',
    aliases: ['spouse birthday', 'partner dob'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'date',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Spouse age context for household and insurance planning.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'family.self.isMarried', eq: true }] },
    state: { path: 'familyMembers[relation=Spouse].dob' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-details',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
  }),

  normalizeField({
    id: 'family.spouse.mobile',
    kind: 'field',
    label: 'Spouse Mobile',
    shortLabel: 'Spouse Mobile',
    aliases: ['spouse phone', 'partner mobile'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'tel',
    importance: 'low',
    quickEditPriority: 'low',
    businessMeaning: 'Spouse contact number for household profile completeness.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'family.self.isMarried', eq: true }] },
    state: { path: 'familyMembers[relation=Spouse].mobile' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-details',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
    tags: ['pii'],
  }),

  normalizeField({
    id: 'family.spouse.isWorking',
    kind: 'field',
    label: 'Is your spouse working?',
    shortLabel: 'Spouse working?',
    aliases: ['spouse employed', 'partner working'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'boolean',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning:
      'Gate for spouse employment details and spouse income capture in Money In & Out.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'family.self.isMarried', eq: true }] },
    state: { path: 'familyMembers[relation=Spouse].isSpouseWorking' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-details',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['income.hasSpouseIncome'],
    impacts: ['engine.income'],
    tags: ['gate'],
  }),

  normalizeField({
    id: 'family.spouse.employmentType',
    kind: 'field',
    label: 'Spouse Employment Type',
    shortLabel: 'Spouse Job Type',
    aliases: ['spouse occupation', 'spouse job'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'enum',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Determines spouse income capture path in detailed cash-flow questions.',
    editExperience: { type: 'question' },
    visibility: {
      allOf: [
        { field: 'family.self.isMarried', eq: true },
        { field: 'family.spouse.isWorking', eq: true },
      ],
    },
    state: {
      path: 'familyMembers[relation=Spouse].employmentType',
      refinements: { syncModule: 'employmentTypeSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-employment',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.income'],
  }),

  normalizeField({
    id: 'family.spouse.retirementAge',
    kind: 'field',
    label: 'Spouse Retirement Age',
    shortLabel: 'Spouse Retire At',
    aliases: ['spouse retirement'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'number',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Spouse planning horizon when dual-income retirement projections are considered.',
    editExperience: { type: 'question' },
    visibility: {
      allOf: [
        { field: 'family.self.isMarried', eq: true },
        { field: 'family.spouse.isWorking', eq: true },
      ],
    },
    state: { path: 'familyMembers[relation=Spouse].retirementAge' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'spouse-employment',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.retirementHorizon'],
  }),

  normalizeField({
    id: 'family.children',
    kind: 'collection',
    label: 'Children',
    shortLabel: 'Children',
    aliases: ['kids', 'child', 'dependents'],
    domain: 'family',
    uiCategory: 'personal_information',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 10,
    businessMeaning:
      'Dependent children drive education expense planning, life-insurance blocks, and goal catalogs.',
    editExperience: { type: 'collection' },
    visibility: { allOf: [{ field: 'family.self.isMarried', eq: true }] },
    state: { path: 'familyMembers[relation=Child]', idKey: 'id' },
    itemFieldIds: [
      'family.child.name',
      'family.child.dob',
      'family.child.occupation',
      'family.child.monthlyEducationExpense',
    ],
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'children',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [
      'report.detail.your_money_flow',
      'engine.education',
      'engine.goals',
    ],
    tags: ['identity', 'dependents'],
  }),

  normalizeField({
    id: 'family.child.name',
    kind: 'collectionItemField',
    collectionId: 'family.children',
    label: 'Child Name',
    shortLabel: 'Child Name',
    aliases: ['kid name'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'text',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Identifies a child dependent for education and insurance planning.',
    editExperience: { type: 'collection', collectionId: 'family.children' },
    state: { path: 'name' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'children',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: [],
  }),

  normalizeField({
    id: 'family.child.dob',
    kind: 'collectionItemField',
    collectionId: 'family.children',
    label: 'Child Date of Birth',
    shortLabel: 'Child DOB',
    aliases: ['child age', 'kid dob'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'date',
    importance: 'high',
    quickEditPriority: 'low',
    businessMeaning: 'Child age informs education timeline and related goal horizons.',
    editExperience: { type: 'collection', collectionId: 'family.children' },
    state: { path: 'dob' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'children',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.education'],
  }),

  normalizeField({
    id: 'family.child.occupation',
    kind: 'collectionItemField',
    collectionId: 'family.children',
    label: 'Studying at (School / College)',
    shortLabel: 'School/College',
    aliases: ['school', 'college', 'studying'],
    domain: 'family',
    uiCategory: 'personal_information',
    valueType: 'enum',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Determines which education cost fields apply for the child.',
    editExperience: { type: 'collection', collectionId: 'family.children' },
    state: { path: 'occupation' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'children',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.education'],
  }),

  normalizeField({
    id: 'family.child.monthlyEducationExpense',
    kind: 'collectionItemField',
    collectionId: 'family.children',
    label: 'Monthly Education Expense',
    shortLabel: 'Child Education Spend',
    aliases: ['school fee', 'college fee', 'tuition'],
    domain: 'family',
    uiCategory: 'expenses',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 8,
    businessMeaning:
      'Per-child monthly education spend rolled into household education totals for cash-flow analysis.',
    editExperience: { type: 'breakdown' },
    state: {
      path: 'monthlyEducationExpense',
      refinements: { syncModule: 'educationExpenseSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'household-breakup',
        capability: 'full',
        role: 'breakdown',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.FAMILY_INFORMATION,
        questionId: 'children',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow', 'engine.education'],
    tags: ['recurring-cashflow', 'education'],
  }),
];
