import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const GOAL_FIELDS = [
  normalizeField({
    id: 'goals.items',
    kind: 'collection',
    label: 'Financial Goals',
    shortLabel: 'Goals',
    aliases: ['goals', 'dreams', 'targets', 'financial goals'],
    domain: 'goals',
    uiCategory: 'goals',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 16,
    businessMeaning:
      'Collection of life goals driving future cost projections, surplus allocation, and Dreams & Goals planning.',
    editExperience: { type: 'collection' },
    savePolicy: { scope: 'collection_instance', recalculate: 'impacts', returnTo: 'origin_report' },
    state: { path: 'goals', idKey: 'id' },
    itemFieldIds: [
      'goals.item.name',
      'goals.item.yearsToGoal',
      'goals.item.presentValue',
    ],
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.GOALS,
        questionId: 'SELECT',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-intro',
        capability: 'full',
        role: 'recap',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-catalog',
        capability: 'full',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-review',
        capability: 'full',
        role: 'recap',
      },
    ],
    preferredSurface: {
      whenCapabilitySummary: 'summary',
      whenCapabilityFull: 'detailed',
    },
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.goals',
      'engine.allocation',
    ],
    tags: ['goals'],
  }),

  normalizeField({
    id: 'goals.item.name',
    kind: 'collectionItemField',
    collectionId: 'goals.items',
    label: 'Goal Name',
    shortLabel: 'Goal',
    aliases: ['goal title', 'goal name'],
    domain: 'goals',
    uiCategory: 'goals',
    valueType: 'text',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 4,
    businessMeaning: 'Display name for a goal instance in reports and allocation narratives.',
    editExperience: { type: 'collection', collectionId: 'goals.items' },
    state: { path: 'name' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.GOALS,
        questionId: 'SELECT',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-catalog',
        capability: 'full',
        role: 'primary',
      },
    ],
    impacts: ['report.summary.future_self', 'engine.goals'],
    tags: ['goals'],
  }),

  normalizeField({
    id: 'goals.item.yearsToGoal',
    kind: 'collectionItemField',
    collectionId: 'goals.items',
    label: 'Years Remaining',
    shortLabel: 'Years',
    aliases: ['years to goal', 'timeline', 'goal years', 'when'],
    domain: 'goals',
    uiCategory: 'goals',
    valueType: 'number',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 12,
    businessMeaning:
      'Time horizon for inflating present value to future cost and sizing monthly goal funding.',
    editExperience: { type: 'collection', collectionId: 'goals.items' },
    state: { path: 'yearsToGoal' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.GOALS,
        questionId: 'YEARS',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-years',
        capability: 'full',
        role: 'primary',
      },
    ],
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.goals',
      'engine.allocation',
    ],
    tags: ['goals', 'planning-horizon'],
  }),

  normalizeField({
    id: 'goals.item.presentValue',
    kind: 'collectionItemField',
    collectionId: 'goals.items',
    label: 'Present Value of Goal',
    shortLabel: 'Goal Value',
    aliases: ['goal cost', 'present value', 'goal amount', 'today cost'],
    domain: 'goals',
    uiCategory: 'goals',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 14,
    businessMeaning:
      'Today’s cost of the goal, inflated over years-to-goal for future funding and surplus allocation.',
    editExperience: { type: 'collection', collectionId: 'goals.items' },
    state: { path: 'presentValue' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.GOALS,
        questionId: 'VALUE',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.DREAMS_AND_GOALS,
        questionId: 'goals-value',
        capability: 'full',
        role: 'primary',
      },
    ],
    impacts: [
      'report.summary.future_self',
      'report.detail.put_your_money_to_work',
      'engine.goals',
      'engine.allocation',
    ],
    tags: ['goals'],
  }),
];
