import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const INCOME_FIELDS = [
  normalizeField({
    id: 'income.self.monthlyTakeHome',
    kind: 'field',
    label: 'Monthly in-hand salary / Take-home profit',
    shortLabel: 'Monthly Salary',
    aliases: ['salary', 'income', 'take home', 'in hand', 'monthly income', 'paycheck'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'high',
    searchBoost: 20,
    businessMeaning:
      'Primary monthly income used by cash flow analysis, tax estimation, allocation engine and retirement projections.',
    editExperience: {
      type: 'question',
      hostsFieldIds: [
        'income.self.monthlyTakeHome',
        'income.hasSpouseIncome',
        'income.spouse.monthlyTakeHome',
      ],
    },
    savePolicy: { scope: 'hosts', recalculate: 'impacts', returnTo: 'origin_report' },
    state: {
      path: 'income.summarySelfInHand',
      legacyPaths: ['income.self'],
      refinements: {
        syncModule: 'incomeDetailSync',
        detailPaths: ['income.selfDetail'],
        reconciliation: 'summaryVsDetail',
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'household-income',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['income.hasSpouseIncome', 'income.spouse.monthlyTakeHome'],
    impacts: [
      'report.summary.money_story',
      'report.detail.your_money_flow',
      'engine.cashFlow',
      'engine.allocation',
    ],
    tags: ['recurring-cashflow'],
  }),

  normalizeField({
    id: 'income.hasSpouseIncome',
    kind: 'field',
    label: 'Does spouse contribute to household income?',
    shortLabel: 'Spouse income?',
    aliases: ['spouse income', 'partner income', 'wife income', 'husband income'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'boolean',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 6,
    businessMeaning:
      'Gate for including spouse take-home in household cash flow and related detailed income questions.',
    editExperience: {
      type: 'question',
      hostsFieldIds: [
        'income.self.monthlyTakeHome',
        'income.hasSpouseIncome',
        'income.spouse.monthlyTakeHome',
      ],
    },
    state: { path: 'hasSpouseIncome' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'household-income',
        capability: 'summary',
        role: 'primary',
      },
    ],
    relatedFieldIds: ['income.self.monthlyTakeHome', 'income.spouse.monthlyTakeHome'],
    impacts: ['report.summary.money_story', 'report.detail.your_money_flow', 'engine.cashFlow'],
    tags: ['recurring-cashflow', 'gate'],
  }),

  normalizeField({
    id: 'income.spouse.monthlyTakeHome',
    kind: 'field',
    label: "Spouse's monthly in-hand salary / Take-home profit",
    shortLabel: 'Spouse Salary',
    aliases: ['spouse salary', 'partner salary', 'spouse take home'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    searchBoost: 10,
    businessMeaning:
      'Secondary household income included in surplus and cash-flow analysis when spouse contributes.',
    editExperience: {
      type: 'question',
      hostsFieldIds: [
        'income.self.monthlyTakeHome',
        'income.hasSpouseIncome',
        'income.spouse.monthlyTakeHome',
      ],
    },
    visibility: {
      allOf: [{ field: 'income.hasSpouseIncome', eq: true }],
    },
    state: {
      path: 'income.summarySpouseInHand',
      legacyPaths: ['income.spouse'],
      refinements: {
        syncModule: 'incomeDetailSync',
        detailPaths: ['income.spouseDetail'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.CASH_FLOW,
        questionId: 'household-income',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['income.hasSpouseIncome', 'income.self.monthlyTakeHome'],
    impacts: ['report.summary.money_story', 'report.detail.your_money_flow', 'engine.cashFlow'],
    tags: ['recurring-cashflow'],
  }),

  // --- Phase 2: Detailed income capture ---

  normalizeField({
    id: 'income.self.needTaxPlanning',
    kind: 'field',
    label: 'Do you need Tax planning?',
    shortLabel: 'Tax planning?',
    aliases: ['tax planning', 'tds', 'salary breakup'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'boolean',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning:
      'Gates detailed salary earnings/deductions capture used for tax estimation and gross-to-net derivation.',
    editExperience: { type: 'question' },
    state: { path: 'income.selfDetail.needTaxPlanning' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.tax'],
    tags: ['tax', 'gate'],
  }),

  normalizeField({
    id: 'income.self.inHandSalary',
    kind: 'field',
    label: 'In-hand salary (detailed)',
    shortLabel: 'In-hand (detail)',
    aliases: ['detailed salary', 'net salary'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'medium',
    businessMeaning:
      'Detailed salaried take-home when tax planning is off, or derived from earnings/deductions when tax planning is on. Syncs to summary take-home.',
    editExperience: { type: 'question' },
    state: {
      path: 'income.selfDetail.inHandSalary',
      refinements: { syncModule: 'incomeDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['income.self.monthlyTakeHome'],
    impacts: [
      'report.detail.your_money_flow',
      'engine.cashFlow',
      'engine.income',
    ],
    tags: ['recurring-cashflow'],
  }),

  normalizeField({
    id: 'income.self.takeHomeProfit',
    kind: 'field',
    label: 'Take-home profit (detailed)',
    shortLabel: 'Profit (detail)',
    aliases: ['business profit', 'professional income'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'medium',
    businessMeaning:
      'Detailed business/professional take-home profit; syncs into summary monthly income for non-salaried paths.',
    editExperience: { type: 'question' },
    state: {
      path: 'income.selfDetail.takeHomeProfit',
      refinements: { syncModule: 'incomeDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow', 'engine.income'],
  }),

  normalizeField({
    id: 'income.self.passiveIncome',
    kind: 'field',
    label: 'Passive Income (rent etc.)',
    shortLabel: 'Passive Income',
    aliases: ['rent income', 'passive'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Additional recurring passive income included in detailed cash-flow.',
    editExperience: { type: 'question' },
    state: { path: 'income.selfDetail.passiveIncome' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'income.self.otherIncome',
    kind: 'collection',
    label: 'Other sources of income',
    shortLabel: 'Other Income',
    aliases: ['additional income', 'other income sources'],
    domain: 'income',
    uiCategory: 'income',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Named other income lines contributing to total monthly inflows.',
    editExperience: { type: 'collection' },
    state: { path: 'income.selfDetail.otherIncome', idKey: 'id' },
    itemFieldIds: ['income.self.otherIncome.amount'],
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow'],
  }),

  normalizeField({
    id: 'income.self.otherIncome.amount',
    kind: 'collectionItemField',
    collectionId: 'income.self.otherIncome',
    label: 'Other income amount',
    shortLabel: 'Other amount',
    aliases: ['other income amount'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Amount for a named other-income line item.',
    editExperience: { type: 'collection', collectionId: 'income.self.otherIncome' },
    state: { path: 'amount' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.cashFlow'],
  }),

  normalizeField({
    id: 'income.self.taxPlanning',
    kind: 'field',
    label: 'Tax earnings & deductions',
    shortLabel: 'Tax breakup',
    aliases: ['basic pay', 'hra', 'pf', 'tax deductions', 'gross salary'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'number',
    importance: 'high',
    quickEditPriority: 'low',
    searchBoost: 6,
    businessMeaning:
      'Aggregated tax-planning earnings and deductions used to derive gross/net salary for salaried users who opt into tax planning.',
    editExperience: { type: 'section' },
    visibility: { allOf: [{ field: 'income.self.needTaxPlanning', eq: true }] },
    state: {
      path: 'income.selfDetail.taxPlanning',
      refinements: { syncModule: 'incomeDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'self-main',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.tax', 'engine.income'],
    tags: ['tax'],
  }),

  normalizeField({
    id: 'income.spouse.detail',
    kind: 'field',
    label: 'Spouse income details',
    shortLabel: 'Spouse income detail',
    aliases: ['spouse detail income', 'partner take home detail'],
    domain: 'income',
    uiCategory: 'income',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning:
      'Detailed spouse income capture (salary/profit/pension/other) syncing to summary spouse take-home.',
    editExperience: { type: 'question' },
    visibility: { allOf: [{ field: 'income.hasSpouseIncome', eq: true }] },
    state: {
      path: 'income.spouseDetail',
      refinements: { syncModule: 'incomeDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'spouse-main',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['income.spouse.monthlyTakeHome'],
    impacts: ['report.detail.your_money_flow', 'engine.cashFlow', 'engine.income'],
  }),
];
