import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const LIABILITY_FIELDS = [
  normalizeField({
    id: 'liabilities.outstandingLoans',
    kind: 'field',
    label: 'Outstanding Loans',
    shortLabel: 'Outstanding Loans',
    aliases: ['loan balance', 'loan outstanding', 'debt outstanding', 'principal outstanding'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    searchBoost: 12,
    businessMeaning:
      'Total loan principal outstanding for net-worth and liability views. Shown when EMI commitments exist; refined per loan in Detailed Flow.',
    editExperience: { type: 'single_value' },
    visibility: {
      allOf: [{ field: 'debt.hasEmi', eq: true }],
    },
    state: {
      path: 'liabilityCategories.summaryOutstandingLoans',
      refinements: {
        syncModule: 'wealthDetailSync',
        detailPaths: ['liabilityCategories.loans'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.LIABILITIES,
        questionId: 'current-liabilities',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    relatedFieldIds: ['debt.hasEmi', 'debt.emi.monthlyTotal'],
    impacts: [
      'report.summary.money_story',
      'report.detail.your_money_flow',
      'engine.netWorth',
    ],
    tags: ['balance-sheet', 'debt'],
  }),

  normalizeField({
    id: 'liabilities.creditCardDues',
    kind: 'field',
    label: 'Credit Card Outstanding',
    shortLabel: 'Credit Card',
    aliases: ['credit card', 'cc dues', 'card outstanding', 'revolving credit'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'high',
    searchBoost: 10,
    businessMeaning:
      'Short-term revolving liability included in net worth and cash pressure assessments.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'liabilityCategories.summaryCreditCardDues',
      refinements: {
        detailPaths: ['liabilityCategories.loans.creditCard'],
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.LIABILITIES,
        questionId: 'current-liabilities',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: ['report.summary.money_story', 'engine.netWorth'],
    tags: ['balance-sheet', 'debt'],
  }),

  normalizeField({
    id: 'liabilities.otherPayables',
    kind: 'field',
    label: 'Other Payables',
    shortLabel: 'Other Payables',
    aliases: ['payables', 'other debt', 'money owed', 'dues'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    searchBoost: 6,
    businessMeaning:
      'Other amounts owed that affect net worth but are not captured as standard loans or credit cards.',
    editExperience: { type: 'single_value' },
    state: { path: 'liabilityCategories.summaryOtherPayables' },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.LIABILITIES,
        questionId: 'current-liabilities',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'wealth-recap',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: ['engine.netWorth'],
    tags: ['balance-sheet'],
  }),

  // --- Phase 2: Liability line items + custom ---

  normalizeField({
    id: 'liabilities.loans.home',
    kind: 'field',
    label: 'Home Loan Outstanding',
    shortLabel: 'Home loan',
    aliases: ['home loan balance', 'housing loan outstanding'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'medium',
    businessMeaning: 'Outstanding home-loan principal in the wealth liability breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'liabilityCategories.loans.home' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'liabilities',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['liabilities.outstandingLoans'],
    impacts: ['engine.netWorth', 'engine.debt'],
  }),

  normalizeField({
    id: 'liabilities.loans.personal',
    kind: 'field',
    label: 'Personal Loan Outstanding',
    shortLabel: 'Personal loan',
    aliases: ['personal loan balance'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Outstanding personal-loan principal in the liability breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'liabilityCategories.loans.personal' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'liabilities',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.netWorth', 'engine.debt'],
  }),

  normalizeField({
    id: 'liabilities.loans.car',
    kind: 'field',
    label: 'Car Loan Outstanding',
    shortLabel: 'Car loan',
    aliases: ['car loan balance', 'auto loan'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Outstanding car-loan principal in the liability breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'liabilityCategories.loans.car' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'liabilities',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'liabilities.loans.education',
    kind: 'field',
    label: 'Education Loan Outstanding',
    shortLabel: 'Education loan',
    aliases: ['education loan balance', 'student loan'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'low',
    businessMeaning: 'Outstanding education-loan principal in the liability breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'liabilityCategories.loans.education' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'liabilities',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'liabilities.loans.creditCard',
    kind: 'field',
    label: 'Credit Card (detailed)',
    shortLabel: 'CC detailed',
    aliases: ['credit card liability'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'high',
    businessMeaning: 'Credit-card outstanding in the detailed liability breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'liabilityCategories.loans.creditCard' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'liabilities',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['liabilities.creditCardDues'],
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'liabilities.custom',
    kind: 'collection',
    label: 'Custom liabilities',
    shortLabel: 'Custom liabilities',
    aliases: ['other liabilities', 'additional payables'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'User-defined liability lines included in net worth.',
    editExperience: { type: 'collection' },
    state: { path: 'liabilityCategories.custom', idKey: 'id' },
    itemFieldIds: ['liabilities.custom.value'],
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'custom-liabilities',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.netWorth'],
  }),

  normalizeField({
    id: 'liabilities.custom.value',
    kind: 'collectionItemField',
    collectionId: 'liabilities.custom',
    label: 'Custom liability value',
    shortLabel: 'Liability value',
    aliases: ['custom liability amount'],
    domain: 'liabilities',
    uiCategory: 'loans_liabilities',
    valueType: 'currency',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'Amount of a user-defined liability line.',
    editExperience: { type: 'collection', collectionId: 'liabilities.custom' },
    state: { path: 'value' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.WEALTH_SNAPSHOT,
        questionId: 'custom-liabilities',
        capability: 'full',
        role: 'primary',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.netWorth'],
  }),
];
