import { SECTION_IDS } from '../../components/FinancialWorkspace/sectionIds';
import { normalizeField } from '../schema';

/** @type {import('../schema').QuestionField[]} */
export const SAVINGS_FIELDS = [
  normalizeField({
    id: 'savings.monthlyInvestments',
    kind: 'field',
    label: 'Monthly Investments',
    shortLabel: 'Monthly Investments',
    aliases: ['sip', 'mutual fund', 'monthly sip', 'investing', 'investments'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'critical',
    quickEditPriority: 'critical',
    searchBoost: 18,
    businessMeaning:
      'Recurring investment outflow used in surplus allocation, future-self projections, and Detailed Flow savings instrument breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: {
      path: 'expenseCategories.summaryMonthlyInvestments',
      refinements: {
        syncModule: 'savingsDetailSync',
        detailPaths: [
          'expenseCategories.savings.sip',
          'expenseCategories.savings.ppf',
          'expenseCategories.savings.nps',
          'expenseCategories.savings.rd',
          'expenseCategories.savings.otherSaving',
        ],
        reconciliation: 'summaryVsDetailSum',
      },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.SAVINGS,
        questionId: 'savings-investments',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-snapshot',
        capability: 'full',
        role: 'recap',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    impacts: [
      'report.summary.money_story',
      'report.summary.future_self',
      'report.detail.your_money_flow',
      'report.detail.put_your_money_to_work',
      'engine.allocation',
    ],
    tags: ['recurring-cashflow', 'investments'],
  }),

  normalizeField({
    id: 'savings.otherMonthlySavings',
    kind: 'field',
    label: 'Other Monthly Savings',
    shortLabel: 'Other Savings',
    aliases: ['fd', 'rd', 'other savings', 'recurring deposit', 'safe savings'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    searchBoost: 10,
    businessMeaning:
      'Additional monthly savings (FDs/RDs and similar) included in cash-flow and wealth-building views.',
    editExperience: { type: 'single_value' },
    state: {
      path: 'expenseCategories.summaryOtherSavings',
      refinements: { syncModule: 'savingsDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'summary',
        sectionId: SECTION_IDS.SAVINGS,
        questionId: 'savings-investments',
        capability: 'summary',
        role: 'primary',
      },
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-snapshot',
        capability: 'full',
        role: 'recap',
      },
    ],
    impacts: [
      'report.summary.money_story',
      'report.detail.your_money_flow',
      'engine.cashFlow',
    ],
    tags: ['recurring-cashflow', 'investments'],
  }),

  // --- Phase 2: Savings instrument breakup ---

  normalizeField({
    id: 'savings.sip',
    kind: 'field',
    label: 'Mutual Fund SIPs',
    shortLabel: 'SIP',
    aliases: ['sip amount', 'mutual fund sip'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'high',
    quickEditPriority: 'high',
    searchBoost: 12,
    businessMeaning:
      'Monthly SIP contribution within the savings breakup; reconciles toward summary monthly investments.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: {
      path: 'expenseCategories.savings.sip',
      refinements: { syncModule: 'savingsDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['savings.monthlyInvestments'],
    impacts: [
      'report.detail.put_your_money_to_work',
      'engine.allocation',
      'engine.cashFlow',
    ],
    tags: ['investments'],
  }),

  normalizeField({
    id: 'savings.ppf',
    kind: 'field',
    label: 'PPF contribution',
    shortLabel: 'PPF',
    aliases: ['ppf', 'public provident fund'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'PPF savings instrument with optional start/duration details via modal.',
    editExperience: {
      type: 'modal',
      modalId: 'investmentDetails',
      allowsInlineFallback: true,
    },
    state: {
      path: 'expenseCategories.savings.ppf',
      refinements: { syncModule: 'savingsDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.allocation'],
    tags: ['investments', 'modal'],
  }),

  normalizeField({
    id: 'savings.nps',
    kind: 'field',
    label: 'NPS contribution',
    shortLabel: 'NPS',
    aliases: ['nps', 'national pension'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'NPS contribution with optional contribution schedule details via modal.',
    editExperience: {
      type: 'modal',
      modalId: 'investmentDetails',
      allowsInlineFallback: true,
    },
    state: {
      path: 'expenseCategories.savings.nps',
      refinements: { syncModule: 'savingsDetailSync' },
    },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.allocation', 'engine.retirementHorizon'],
    tags: ['investments', 'modal'],
  }),

  normalizeField({
    id: 'savings.rd',
    kind: 'collection',
    label: 'Recurring Deposits',
    shortLabel: 'RD',
    aliases: ['rd', 'recurring deposit'],
    domain: 'savings',
    uiCategory: 'investments',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Recurring deposit instruments with amount/duration configured via modal.',
    editExperience: {
      type: 'modal',
      modalId: 'investmentDetails',
      collectionId: 'savings.rd',
    },
    state: { path: 'expenseCategories.savings.rd', idKey: 'id' },
    itemFieldIds: ['savings.rd.amount'],
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.allocation', 'engine.cashFlow'],
    tags: ['investments', 'modal'],
  }),

  normalizeField({
    id: 'savings.rd.amount',
    kind: 'collectionItemField',
    collectionId: 'savings.rd',
    label: 'RD amount',
    shortLabel: 'RD amount',
    aliases: ['rd installment'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'medium',
    quickEditPriority: 'medium',
    businessMeaning: 'Installment amount for a recurring deposit.',
    editExperience: { type: 'modal', modalId: 'investmentDetails', collectionId: 'savings.rd' },
    state: { path: 'amount' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    impacts: ['engine.cashFlow'],
  }),

  normalizeField({
    id: 'savings.otherSaving',
    kind: 'field',
    label: 'Any other saving',
    shortLabel: 'Other saving',
    aliases: ['other saving', 'misc savings'],
    domain: 'savings',
    uiCategory: 'investments',
    valueType: 'currency',
    importance: 'low',
    quickEditPriority: 'medium',
    businessMeaning: 'Catch-all other monthly saving amount in the savings breakup.',
    editExperience: { type: 'breakdown', allowsInlineFallback: true },
    state: { path: 'expenseCategories.savings.otherSaving' },
    editSurfaces: [
      {
        flow: 'detailed',
        sectionId: SECTION_IDS.MONEY_IN_MONEY_OUT,
        questionId: 'savings-breakdown',
        capability: 'full',
        role: 'breakdown',
      },
    ],
    preferredSurface: { whenCapabilitySummary: 'summary', whenCapabilityFull: 'detailed' },
    relatedFieldIds: ['savings.otherMonthlySavings'],
    impacts: ['engine.cashFlow'],
  }),
];
