/**
 * Phase 1 coach-style push notification definitions.
 * Copy + metadata only — evaluation lives in triggerEvaluators.js.
 */

/** @type {object[]} */
export const PHASE1_NOTIFICATIONS = [
  {
    id: 'coach.wealthMapUpdated',
    version: 1,
    category: 'progress',
    event: 'WEALTHMAP_RECALCULATED',
    title: 'Your WealthMap has been updated',
    body: "See what's changed in your financial plan.",
    variants: [
      {
        id: 'A',
        title: 'Your WealthMap has been updated',
        body: "See what's changed in your financial plan.",
        weight: 1,
      },
    ],
    deepLinkId: 'workspace.default',
    enabled: true,
    frequency: {
      type: 'cooldown',
      cooldownHours: 24,
    },
    placeholders: [],
    analyticsKey: 'coach.wealthMapUpdated',
    channel: 'push',
    channels: ['push', 'in_app'],
    priority: 1,
    requiresOptIn: true,
    tags: ['coach', 'phase1'],
    businessMeaning:
      'Nudge after meaningful plan changes once recalculation succeeds — highest-priority progress signal.',
  },
  {
    id: 'coach.protectionGapAttention',
    version: 1,
    category: 'coaching',
    event: 'PROTECTION_GAP_UNRESOLVED',
    title: 'Your family may need more protection',
    body: 'Review your protection gap and see what needs attention.',
    variants: [
      {
        id: 'A',
        title: 'Your family may need more protection',
        body: 'Review your protection gap and see what needs attention.',
        weight: 1,
      },
    ],
    deepLinkId: 'report.protectionGap',
    enabled: true,
    frequency: {
      type: 'cooldown',
      cooldownDays: 30,
      resetOnMeaningfulChange: true,
      changeFingerprintKey: 'protectionGapFingerprint',
    },
    placeholders: [],
    analyticsKey: 'coach.protectionGapAttention',
    channel: 'push',
    channels: ['push', 'in_app'],
    priority: 10,
    requiresOptIn: true,
    tags: ['coach', 'phase1', 'protection'],
    businessMeaning: 'Coach when a protection gap exists and remains unresolved.',
  },
  {
    id: 'coach.surplusAvailable',
    version: 1,
    category: 'coaching',
    event: 'SURPLUS_INVESTABLE',
    title: 'Money waiting to grow',
    body: 'You have ₹{{amount}} available to put to work.',
    variants: [
      {
        id: 'A',
        title: 'Money waiting to grow',
        body: 'You have ₹{{amount}} available to invest.',
        weight: 1,
      },
      {
        id: 'B',
        title: 'Your surplus is ready',
        body: 'Put your extra ₹{{amount}} to work today.',
        weight: 1,
      },
    ],
    deepLinkId: 'report.putMoneyToWork',
    enabled: true,
    frequency: {
      type: 'calendar_month',
      maxPerMonth: 1,
    },
    placeholders: ['amount'],
    analyticsKey: 'coach.surplusAvailable',
    channel: 'push',
    channels: ['push', 'in_app'],
    priority: 20,
    requiresOptIn: true,
    tags: ['coach', 'phase1', 'surplus'],
    businessMeaning: 'Coach when monthly surplus is positive and investable.',
  },
  {
    id: 'coach.goalFallingBehind',
    version: 1,
    category: 'reminders',
    event: 'GOAL_BEHIND_SCHEDULE',
    title: 'One of your goals needs attention',
    body: 'Review your plan to stay on track.',
    variants: [
      {
        id: 'A',
        title: 'One of your goals needs attention',
        body: 'Review your plan to stay on track.',
        weight: 1,
      },
    ],
    deepLinkId: 'report.goals',
    enabled: true,
    frequency: {
      type: 'per_scope_cooldown',
      cooldownDays: 14,
      scopeKey: 'goalId',
    },
    placeholders: [],
    analyticsKey: 'coach.goalFallingBehind',
    channel: 'push',
    channels: ['push', 'in_app'],
    priority: 15,
    requiresOptIn: true,
    tags: ['coach', 'phase1', 'goals'],
    businessMeaning: 'Coach when the goal engine marks a goal behind schedule.',
  },
  {
    id: 'coach.monthlyWealthSummary',
    version: 1,
    category: 'milestones',
    event: 'MONTHLY_WEALTH_SUMMARY_READY',
    title: 'Your monthly Wealth Summary is ready',
    body: "See where your money went and what's next.",
    variants: [
      {
        id: 'A',
        title: 'Your monthly Wealth Summary is ready',
        body: "See where your money went and what's next.",
        weight: 1,
      },
    ],
    deepLinkId: 'report.monthlySummary',
    enabled: true,
    frequency: {
      type: 'calendar_month',
      maxPerMonth: 1,
    },
    placeholders: [],
    analyticsKey: 'coach.monthlyWealthSummary',
    channel: 'push',
    channels: ['push', 'in_app'],
    priority: 30,
    requiresOptIn: true,
    tags: ['coach', 'phase1', 'summary'],
    businessMeaning: 'Milestone when the monthly financial summary becomes available.',
  },
];
